### ISSUE TITLE
The spec of params

### ISSUE THREAD

**Issue by kenjis** [newmythmedia/bay#4]
Now `$params` is array.

```
class Posts {
    public function recentPosts( array $params=[] ) 
    { 
        $limit = ! empty($params['limit']) ? $params['limit'] : 5;
        $offset = ! empty($params['offset']) ? $params['offset'] : 0;

        $posts = $this->postModel->findLatest( $limit, $offset );
        return $this->view('recentPosts', ['posts' => $posts] );
    }
}

// In your view layer...
$bay->display("\Blog\Posts::recentPosts", "limit=5 offset=0");
```

But I hope like this:

```
class Posts {
    public function recentPosts($limit, $offset) 
    { 
        $posts = $this->postModel->findLatest( $limit, $offset );
        return $this->view('recentPosts', ['posts' => $posts] );
    }
}

// In your view layer...
$bay->display("\Blog\Posts::recentPosts", "limit=5 offset=0");
```

**Comment by lonnieezell** [comment]
The reason it works like it currently does is to allow for parameters to be sent in any order to the function. It was modeled after the way the ModX works since I always use to love that aspect of that CMS.

I had considered allowing parameters to be sent as arguments to the function, but working with that and caching was too complex.

At this time, I'm not interesting in changing the way this works since I think it's most convenient in the display layer this way.

**Comment by kenjis** [comment]
Okay. Then how about this? #5
